// <auto-generated />
using System;
using DataServiceLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataServiceLayer.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20251101141228_PlaylistTimeStamps")]
    partial class PlaylistTimeStamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "media_type", new[] { "tvShort", "movie", "tvMovie", "short", "tvMiniSeries", "videoGame", "tvEpisode", "video", "tvSpecial", "tvSeries" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "title_type", new[] { "working", "original", "", "imdbDisplayfestival", "workingalternative", "dvd", "imdbDisplay", "tv", "imdbDisplaydvd", "alternative", "festival", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataServiceLayer.Models.DvdRelease", b =>
                {
                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("MediaId")
                        .HasName("dvd_releases_pkey");

                    b.ToTable("dvd_releases", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Episode", b =>
                {
                    b.Property<string>("EpisodeMediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("episode_media_id");

                    b.Property<string>("SeriesMediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("series_media_id");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.HasKey("EpisodeMediaId", "SeriesMediaId")
                        .HasName("episodes_pkey");

                    b.HasIndex("SeriesMediaId");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.FavoriteMedia", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "MediaId")
                        .HasName("favorite_media_pkey");

                    b.HasIndex("MediaId");

                    b.ToTable("favorite_media", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.FavoritePerson", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PeopleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("people_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "PeopleId")
                        .HasName("favorite_people_pkey");

                    b.HasIndex("PeopleId");

                    b.ToTable("favorite_people", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genres_pkey");

                    b.HasIndex(new[] { "Name" }, "genres_name_key")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Media", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AgeRating")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age_rating");

                    b.Property<decimal?>("AverageRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("average_rating");

                    b.Property<string>("Awards")
                        .HasColumnType("text")
                        .HasColumnName("awards");

                    b.Property<string>("BoxOffice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("box_office");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<decimal?>("ImdbAverageRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("imdb_average_rating");

                    b.Property<int?>("ImdbNumberOfVotes")
                        .HasColumnType("integer")
                        .HasColumnName("imdb_number_of_votes");

                    b.Property<string>("Metascore")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metascore");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("Poster")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("poster");

                    b.Property<string>("Production")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("production");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("media_pkey");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.MediaLanguage", b =>
                {
                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<string>("LanguageName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language_name");

                    b.HasKey("MediaId", "LanguageName")
                        .HasName("media_languages_pkey");

                    b.ToTable("media_languages", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.MediaPerson", b =>
                {
                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<string>("PeopleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("people_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Characters")
                        .HasColumnType("text")
                        .HasColumnName("characters");

                    b.Property<string>("JobNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_note");

                    b.Property<bool?>("KnownFor")
                        .HasColumnType("boolean")
                        .HasColumnName("known_for");

                    b.Property<int?>("Ordering")
                        .HasColumnType("integer")
                        .HasColumnName("ordering");

                    b.HasKey("MediaId", "PeopleId", "RoleId")
                        .HasName("media_people_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "PeopleId" }, "idx_media_people_people_id");

                    b.ToTable("media_people", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<int?>("BirthDate")
                        .HasColumnType("integer")
                        .HasColumnName("birth_date");

                    b.Property<int?>("DeathDate")
                        .HasColumnType("integer")
                        .HasColumnName("death_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("NameRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("name_rating");

                    b.HasKey("Id")
                        .HasName("people_pkey");

                    b.HasIndex(new[] { "Name" }, "idx_people_name");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("playlists_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.HasKey("Id")
                        .HasName("playlist_items_pkey");

                    b.HasIndex("MediaId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("playlist_items", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Rating", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Rating1")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "MediaId")
                        .HasName("ratings_pkey");

                    b.HasIndex(new[] { "MediaId" }, "idx_ratings_media_id");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.RecentlyViewed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<string>("PeopleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("people_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("recently_viewed_pkey");

                    b.HasIndex("MediaId");

                    b.HasIndex("PeopleId");

                    b.HasIndex(new[] { "UserId" }, "idx_recently_viewed_user_id");

                    b.ToTable("recently_viewed", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Review", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("review_text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "MediaId")
                        .HasName("reviews_pkey");

                    b.HasIndex("MediaId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "idx_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("search_history_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_search_history_user_id");

                    b.ToTable("search_history", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<int?>("Ordering")
                        .HasColumnType("integer")
                        .HasColumnName("ordering");

                    b.Property<string>("Region")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("region");

                    b.Property<string>("Title1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("titles_pkey");

                    b.HasIndex(new[] { "MediaId" }, "idx_titles_media_id");

                    b.HasIndex(new[] { "Title1" }, "idx_titles_title");

                    b.ToTable("titles", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.TitleAttribute", b =>
                {
                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.HasKey("TitleId")
                        .HasName("title_attributes_pkey");

                    b.ToTable("title_attributes", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Username" }, "idx_users_username");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.UserList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("lists_pkey");

                    b.HasIndex(new[] { "Title" }, "idx_lists_title");

                    b.HasIndex(new[] { "UserId" }, "idx_lists_user_id");

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.WatchHistory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "MediaId")
                        .HasName("watch_history_pkey");

                    b.HasIndex("MediaId");

                    b.ToTable("watch_history", (string)null);
                });

            modelBuilder.Entity("MediaGenre", b =>
                {
                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("MediaId", "GenreId")
                        .HasName("media_genres_pkey");

                    b.HasIndex("GenreId");

                    b.ToTable("media_genres", (string)null);
                });

            modelBuilder.Entity("MediaListsRel", b =>
                {
                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<string>("MediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_id");

                    b.HasKey("ListId", "MediaId")
                        .HasName("media_lists_rel_pkey");

                    b.HasIndex("MediaId");

                    b.ToTable("media_lists_rel", (string)null);
                });

            modelBuilder.Entity("PeopleListsRel", b =>
                {
                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<string>("PeopleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("people_id");

                    b.HasKey("ListId", "PeopleId")
                        .HasName("people_lists_rel_pkey");

                    b.HasIndex("PeopleId");

                    b.ToTable("people_lists_rel", (string)null);
                });

            modelBuilder.Entity("DataServiceLayer.Models.DvdRelease", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithOne("DvdRelease")
                        .HasForeignKey("DataServiceLayer.Models.DvdRelease", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("dvd_releases_media_id_fkey");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Episode", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "EpisodeMedia")
                        .WithMany("EpisodeEpisodeMedia")
                        .HasForeignKey("EpisodeMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("episodes_episode_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Media", "SeriesMedia")
                        .WithMany("EpisodeSeriesMedia")
                        .HasForeignKey("SeriesMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("episodes_series_media_id_fkey");

                    b.Navigation("EpisodeMedia");

                    b.Navigation("SeriesMedia");
                });

            modelBuilder.Entity("DataServiceLayer.Models.FavoriteMedia", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("FavoriteMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorite_media_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("FavoriteMedia")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorite_media_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.FavoritePerson", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Person", "People")
                        .WithMany("FavoritePeople")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorite_people_people_id_fkey");

                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("FavoritePeople")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorite_people_user_id_fkey");

                    b.Navigation("People");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.MediaLanguage", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("MediaLanguages")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_languages_media_id_fkey");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DataServiceLayer.Models.MediaPerson", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("MediaPeople")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_people_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Person", "People")
                        .WithMany("MediaPeople")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_people_people_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Role", "Role")
                        .WithMany("MediaPeople")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("media_people_role_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("People");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Playlist", b =>
                {
                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("playlists_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.PlaylistItem", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("playlist_items_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Playlist", "Playlist")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("playlist_items_playlist_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Rating", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ratings_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ratings_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.RecentlyViewed", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("RecentlyVieweds")
                        .HasForeignKey("MediaId")
                        .HasConstraintName("recently_viewed_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Person", "People")
                        .WithMany("RecentlyVieweds")
                        .HasForeignKey("PeopleId")
                        .HasConstraintName("recently_viewed_people_id_fkey");

                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("RecentlyVieweds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("recently_viewed_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("People");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Review", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("Reviews")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_user_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Rating", "Rating")
                        .WithOne("Review")
                        .HasForeignKey("DataServiceLayer.Models.Review", "UserId", "MediaId")
                        .IsRequired()
                        .HasConstraintName("reviews_user_id_media_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("Rating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.SearchHistory", b =>
                {
                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("search_history_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Title", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("Titles")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("titles_media_id_fkey");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DataServiceLayer.Models.TitleAttribute", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Title", "Title")
                        .WithOne("TitleAttribute")
                        .HasForeignKey("DataServiceLayer.Models.TitleAttribute", "TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("title_attributes_title_id_fkey");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("DataServiceLayer.Models.UserList", b =>
                {
                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("lists_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataServiceLayer.Models.WatchHistory", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Media", "Media")
                        .WithMany("WatchHistories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("watch_history_media_id_fkey");

                    b.HasOne("DataServiceLayer.Models.User", "User")
                        .WithMany("WatchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("watch_history_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaGenre", b =>
                {
                    b.HasOne("DataServiceLayer.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_genres_genre_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_genres_media_id_fkey");
                });

            modelBuilder.Entity("MediaListsRel", b =>
                {
                    b.HasOne("DataServiceLayer.Models.UserList", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_lists_rel_list_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_lists_rel_media_id_fkey");
                });

            modelBuilder.Entity("PeopleListsRel", b =>
                {
                    b.HasOne("DataServiceLayer.Models.UserList", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("people_lists_rel_list_id_fkey");

                    b.HasOne("DataServiceLayer.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("people_lists_rel_people_id_fkey");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Media", b =>
                {
                    b.Navigation("DvdRelease");

                    b.Navigation("EpisodeEpisodeMedia");

                    b.Navigation("EpisodeSeriesMedia");

                    b.Navigation("FavoriteMedia");

                    b.Navigation("MediaLanguages");

                    b.Navigation("MediaPeople");

                    b.Navigation("PlaylistItems");

                    b.Navigation("Ratings");

                    b.Navigation("RecentlyVieweds");

                    b.Navigation("Reviews");

                    b.Navigation("Titles");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Person", b =>
                {
                    b.Navigation("FavoritePeople");

                    b.Navigation("MediaPeople");

                    b.Navigation("RecentlyVieweds");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistItems");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Rating", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Role", b =>
                {
                    b.Navigation("MediaPeople");
                });

            modelBuilder.Entity("DataServiceLayer.Models.Title", b =>
                {
                    b.Navigation("TitleAttribute");
                });

            modelBuilder.Entity("DataServiceLayer.Models.User", b =>
                {
                    b.Navigation("FavoriteMedia");

                    b.Navigation("FavoritePeople");

                    b.Navigation("Lists");

                    b.Navigation("Playlists");

                    b.Navigation("Ratings");

                    b.Navigation("RecentlyVieweds");

                    b.Navigation("Reviews");

                    b.Navigation("SearchHistories");

                    b.Navigation("WatchHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
